# Generated by Django 4.1.7 on 2023-05-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('district', models.CharField(choices=[('1', 'DHAKA'), ('2', 'CHITTAGONG'), ('3', 'KHULNA'), ('4', 'RAJSHAHI'), ('5', 'BARISHAL'), ('6', 'DINAJPUR'), ('7', 'RANGPUR')], default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=100)),
                ('post', models.TextField()),
                ('post_time', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(default=None, max_length=50)),
                ('emergency', models.BooleanField(default=False)),
            ],
        ),
    ]
