# Generated by Django 4.1.7 on 2023-06-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('district', models.CharField(choices=[('Dhaka', 'DHAKA'), ('Chittagong', 'CHITTAGONG'), ('Khulna', 'KHULNA'), ('Rajshahi', 'RAJSHAHI'), ('Barishal', 'BARISHAL'), ('Dinajpur', 'DINAJPUR'), ('Rangpur', 'RANGPUR')], default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('area', models.CharField(default=None, max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=50)),
                ('post_time', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(default=None, max_length=50)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
